title: Santtu Välimäki
logo: /assets/img/santtu.png
description: It's not about throwing around some fancy tech acronyms. It's about seeing the bigger picture, understanding what is required, solving the right problems with the right tools and in the best case delivering beyond expectations.
theme: jekyll-theme-minimal
