title: Santtu Välimäki
logo: /assets/img/santtu.png
description: <i>"It's not about fancy tech acronyms - it's about seeing the bigger picture, understanding what is required, solving the right problems and in the best case delivering beyond expectations."</i>
theme: jekyll-theme-minimal
